spring:
  datasource:
    driver: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://sql_server:1433;databaseName=todolistdb;trustServerCertificate=true
    password: ProjectTodoStefanini#2024
    username: SA
    hikari:
      connection-timeout: 35000

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

flyway:
  enabled: true
  url: jdbc:sqlserver://sql_server:1433;databaseName=todolistdb;trustServerCertificate=true
  username: SA
  password: ProjectTodoStefanini#2024
  locations: classpath:db/migration

