spring:
  datasource:
    driver: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://database-todolist.cj2camc8unmp.us-east-1.rds.amazonaws.com;databaseName=todolistdb;trustServerCertificate=true
    password: ProjectTodoStefanini#2024RDS
    username: admin

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

flyway:
  enabled: true
  url: jdbc:sqlserver://database-todolist.cj2camc8unmp.us-east-1.rds.amazonaws.com;databaseName=todolistdb;trustServerCertificate=true
  username: admin
  password: ProjectTodoStefanini#2024RDS
  locations: classpath:db/migration

