#Docker compose com os 2 containers para deploy em ambiente de desenvolvimento. O banco de dados aqui foi usado no Amazon RDS.

services:
  app_spring_todolist:
    networks:
      - spring-app-todolist-network
    tty: true
    container_name: spring-app-todolist-container
    image: halfgui/todolist-spring:develop
    environment:
      - SPRING_PROFILE=dev
  nginx:
    image: halfgui/todolist-nginx:develop
    container_name: nginx-todolist
    networks:
      - spring-app-todolist-network
    ports:
      - "8082:80"
    depends_on:
      - app_spring_todolist


networks:
  spring-app-todolist-network:
    driver: bridge
