# Este docker-compose foi feito com a exclusividade de criar o banco de dados localmente para conexão através de rodar a
# API no intellij ou o .jar compilado da aplicação com a variável local ativada.

version: '3.7'

services:
  sql_server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server_local_container
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
      - MSSQL_SA_PASSWORD=ProjectTodoStefanini#2024
    ports:
      - "1433:1433"
    command: /bin/bash ./entrypoint.sh
    volumes:
      - ./data:/var/opt/mssql/data
      - ./init-scripts/entrypoint.sh:/entrypoint.sh
      - ./init-scripts/initdb.sh:/initdb.sh
      - ./init-scripts/initdb.sql:/initdb.sql


# Comando para rodar docker compose --> docker compose -p containers-stefanini -f docker-compose.local.yaml up
