#Docker compose com os 3 containers para rodar a aplicação de maneira completa localmente.
version: '3.7'

services:
  sql_server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server_container
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
      - MSSQL_SA_PASSWORD=ProjectTodoStefanini#2024
    ports:
      - "1433:1433"
    command: /bin/bash ./entrypoint.sh
    networks:
      - spring-app-todolist-network
    volumes:
      - ./data:/var/opt/mssql/data
      - ./init-scripts/entrypoint.sh:/entrypoint.sh
      - ./init-scripts/initdb.sh:/initdb.sh
      - ./init-scripts/initdb.sql:/initdb.sql
  app_spring_todolist:
    build:
      context: ../../../../
      dockerfile: Dockerfile
    networks:
      - spring-app-todolist-network
    tty: true
    container_name: spring-app-todolist-container
    image: halfgui/todolist-spring:develop
    environment:
      - SPRING_PROFILE=local-completo
    depends_on:
      - sql_server
  nginx:
    build:
      context: ../../../../
      dockerfile: Dockerfile-nginx
    image: halfgui/todolist-nginx:develop
    container_name: nginx-todolist
    networks:
      - spring-app-todolist-network
    ports:
      - "8082:80"
    depends_on:
      - app_spring_todolist


networks:
  spring-app-todolist-network:
    driver: bridge


# Comando para rodar docker compose --> docker compose -p containers-stefanini -f docker-compose.local-completo.yaml up
# Comando para rodar docker compose buildando imagens conjuntamente --> docker compose -p containers-stefanini -f docker-compose.local-completo.yaml  up --build