name: Build run tests and push docker images

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build Maven Project
        run: mvn clean package

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Build and Push Spring Docker Image to DockerHub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: halfgui/todolist-spring
      
      - name: Build and Push Nginx Docker Image to DockerHub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.nginx
          push: true
          tags: halfgui/todolist-spring

      # Add similar steps for building and pushing the Nginx Docker image if you have one.
      # - name: Build and Push Nginx Docker Image
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: path/to/nginx/project
      #     file: Dockerfile
      #     push: true
      #     tags: your-dockerhub-username/your-nginx-project:latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
